title: EngineerCV
show_downloads: true
baseurl: '/engineer-cv' #change it according to your repository name


code: https://github.com/fanghuagu/engineer-cv
zip_url: https://github.com/fanghuagu/engineer-cv
tar_url: https://github.com/fanghuagu/engineer-cv
github: https://github.com/fanghuagu


